### ISSUE TITLE
Saving fooling images

### ISSUE THREAD

**Issue by neale** [openai/cleverhans#123]
How can I save only the images generated from either FGSM or JSMA attacks? 

It looks like the tensor of images returned out of `batch_eval(sess, [x], [adv_x], [X_train], args=eval_params)` only give the noise that will be added to the original images.

I'm training a detector, and this library looks much better than the way I was generating fooling images before. I just can't figure out how to get the actual perturbed images. 

Thanks.

**Comment by goodfeli** [comment]
`adv_x` as defined in the tutorials is actually the images generated by FGSM, like you want.

`batch_eval` will evaluate any graph you pass to it, so you could use it to generate either the adversarial images or just the perturbations.
