### ISSUE TITLE
cleverhans devs: developer tools collection that may be of use - WIP

### ISSUE THREAD

**Issue by stephenbhope** [openai/cleverhans#126]
I am working on stephenbhope/Revised-CommAI-env and as part of the process unified end user & developer tool box highlighting outstanding examples of opensource apps. Are there any wish list items from contributors here for either finding the right tool or to automate a tedious bit? I want to make the tool box a stop when developers are looking for something different to their current tools, or empty spots in their set.

I'd be happy to assist with setting up the webhooks to link this repo to any of github's testing, linting apps if it's wanted.

**Comment by npapernot** [comment]
Thank you Stephen, this thread would be more appropriate for discussion within the developer ML at cleverhans-dev@googlegroups.com

I am closing this for now, as this is not related to a bug/issue about cleverhans
