### ISSUE TITLE
Remove keras from MNIST dataset loader

### ISSUE THREAD

**Issue by npapernot** [openai/cleverhans#128]
In `cleverhans.utils_mnist`, keras is used to  load MNIST. We could directly download from its website and remove all dependencies on keras

**Comment by Duncanswilson** [comment]
since you all use tf, couldn't you also load it like this:
`
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)
`
?

**Comment by npapernot** [comment]
Thanks for the code snippet. 

You are right, this would be the way to go once Theano support is deprecated. We recently proposed to drop Theano support (https://groups.google.com/forum/#!topic/cleverhans-dev/xXqAG97RTfo), so we will soon be able to assume that all users are running TensorFlow. 

It is probably easier to hold on for the PR that will deprecate Theano before resolving this issue
