### ISSUE TITLE
Question regarding replication

### ISSUE THREAD

**Issue by RiaanZoetmulder** [openai/cleverhans#130]
Hello,

I have made my own little implementation of some of the methods described here (using some of your code as an example). I have a specific question regarding the Fast Gradient Sign method.

I have set epsilon to 0.3 as per the example. About 97.5 percent of my predicted labels change. This should be good. However on Cifar 10, the images become quite pixelated due to this. Is this supposed to happen? I thought the perturbations were invisible to the naked eye.

The convnet I am using uses 3 convolutional layers and 1 softmax layer with relu activations.

regards,

Riaan

**Comment by npapernot** [comment]
Hi Riaan, 

The value of the parameter epsilon should be set depending on the input domain you are working with. It lets you trade-off the chances of having the input misclassified with the magnitude of the perturbation introduced. The impact of an epsilon parameter of 0.3 on your CIFAR data will depend on how you pre-processed it before training your model. Have you tried reducing the value of epsilon?

You may want to check https://github.com/openai/cleverhans/blob/master/examples/ex_cifar10_tf.py and ping @paulhendricks 

Cheers

**Comment by RiaanZoetmulder** [comment]
I have tried various values for epsilon. between 0.007 up until 0.3 . I preprocess the data by dividing it by 255.0. With for example 0.07, approximately 70% of the labels changes! The lower I go, the less the likelihood of the prediction changing!

And yes I am using that code to replicate your research! If you wish, I can send you what I have done, although I don't want to impose!

@paulhendricks
