### ISSUE TITLE
Initialization error for /tutorial/mnist_blackbox.py

### ISSUE THREAD

**Issue by leviswind** [openai/cleverhans#133]
Before the training process of substitute network, the oracle network was trained with the same session with the substitute network, so when training the substitute network with
```
def train_sub(sess, x, y, bbox_preds, X_sub, Y_sub):
```
it initialize all variables not only in substitute network, but also the variables in oracle network. So the training process of oracle network is useless.
```
if hasattr(tf, "global_variables_initializer"):
            tf.global_variables_initializer().run()
        else:
            warnings.warn("Update your copy of tensorflow; future versions of "
                          "cleverhans may drop support for this version.")
            sess.run(tf.initialize_all_variables())
```
So it can't prove the adversarial examples generated by the substitute network fools the oracle network for the oracle network is randomly initialized after the training of substitute network.
Can anyone tell me that is it understood correctly?
I think the initialization should be like this
```
def initialize_uninitialized(sess):
       global_vars = tf.global_variables()
       is_not_initialized = sess.run([tf.is_variable_initialized(var) for var in global_vars])
       not_initialized_vars = [v for (v, f) in zip(global_vars, is_not_initialized) if not f]
       print([str(i.name) for i in not_initialized_vars]) # only for testing
       if len(not_initialized_vars):
            sess.run(tf.variables_initializer(not_initialized_vars))
 with sess.as_default():
       if hasattr(tf, "global_variables_initializer"):
            initialize_uninitialized(sess)
```

**Comment by npapernot** [comment]
Thank you for pointing this out, let us know if #135 fixes this bug on your side as well. I based it off the snippet you shared.

**Comment by leviswind** [comment]
I run the mnist_blackbox.py after the modification, but the result if as follows
```
Test accuracy of oracle on adversarial examples generated using the substitute: 0.770964466957
```
if we replace the relatively complicated Jacobian-based dataset augmentation with simply repetition of training set at last step,
```
# X_sub = jacobian_augmentation(sess, x, X_sub, Y_sub, grads,
#                                                     FLAGS.lmbda)
X_sub = np.concatenate([X_sub, X_sub], axis=0)
```
```
Test accuracy of oracle on adversarial examples generated using the substitute: 0.690152283574
```
the result is relatively better, which means the Jacobian-based dataset 
augmentation has not effect for better adversarial examples generation. 

Is there something wrong with the implementation?

**Comment by dribnet** [comment]
Narrator: the bug likely responsible for @leviswind's observation was later found (#321)
