### ISSUE TITLE
create a dataset iterator

### ISSUE THREAD

**Issue by npapernot** [openai/cleverhans#21]
Create an iterator so one can write `for batch_index in dataset`

**Comment by goodfeli** [comment]
Does MILA labs' fuel already provide something like this? (@dwf?)

Does keras provide anything similar?

For tensorflow implementations, we probably want a queue op, not a python iterator.

**Comment by npapernot** [comment]
I'm closing this for now, feel free to reopen if you feel like it's important to have this feature
