### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by goodfeli** [openai/cleverhans#32]
We should do a new release with a major version increment because of #25 . Because the loss was used as part of the attacks, this bug made the attacks appear too weak.

**Comment by npapernot** [comment]
Agreed, should we wait to get the saliency map attack and update the tech report at the same time?

**Comment by goodfeli** [comment]
Yes, I think so.
Also, I found another bug, in the evaluation metric. Sending a pull request in a few minutes. So we can bundle all of that into one update.

**Comment by npapernot** [comment]
https://github.com/openai/cleverhans/releases/tag/v1.0.0
