### ISSUE TITLE
create coding style

### ISSUE THREAD

**Issue by npapernot** [openai/cleverhans#39]
note to self: two empty lines before each function

**Comment by npapernot** [comment]
space after commas in tuples

**Comment by goodfeli** [comment]
Should we just say to use PEP8, instead of making a cleverhans-specific style guide?

**Comment by npapernot** [comment]
Sgtm, I'll mention it in the main readme

**Comment by npapernot** [comment]
added in 8146dd4e7181ccdf347b7d5ca584f413e2bc469d
