### ISSUE TITLE
JSMA API suggestion

### ISSUE THREAD

**Issue by gongzhitaao** [openai/cleverhans#53]
IMHO, there might be a couple of improvements over the JSMA API.

1. `increase` and `theta` are duplicates.
`increase=True` <-> `theta=+x`
`increase=False` <-> `theta=-x`
2. `jacobian_graph` is like a loose ends to me.
I think the gradients should be calculated internally in the JSMA function, it is, at least to me, counter-intuitive to called some random function before calling the `jsma`.

**Comment by npapernot** [comment]
regardin 2. this is not possible otherwise everytime we make a new call to jsma in order to craft a new adversarial example, we will create new TF graph elements and make the operations slower and slower at each call of jsma

**Comment by gongzhitaao** [comment]
Actually TF provides a [tf.while_loop](https://www.tensorflow.org/api_docs/python/control_flow_ops/control_flow_operations#while_loop) to achieve this.  I have an example implementation of JSMA with tf.while_loop, please see [here](https://github.com/gongzhitaao/tensorflow-adversarial/blob/master/attacks/jsma.py#L59).

**Comment by npapernot** [comment]
This will get addressed by the new API in preparation.
