### ISSUE TITLE
unused learning_phase in batch_eval

### ISSUE THREAD

**Issue by kudkudak** [openai/cleverhans#56]
`batch_eval` in `utils_th` (https://github.com/openai/cleverhans/blob/master/cleverhans/utils_th.py#L167) throws an error if computation graph doesn't use `learning_phase`. Way to fix that would be to add `on_unused_input='ignore'` to arguments of `theano.function` call.

**Comment by npapernot** [comment]
@kudkudak Do you think you can make a PR for this?

**Comment by kudkudak** [comment]
Will do! But after ICLR workshop deadline :)

**Comment by npapernot** [comment]
Thanks !

**Comment by npapernot** [comment]
@kudkudak anything new regarding this issue?

**Comment by kudkudak** [comment]
Sorry :) I sit to it this weekend

2017-03-23 22:19 GMT+01:00 Nicolas Papernot <notifications@github.com>:

**Comment by npapernot** [comment]
No worries, your help is appreciated :)
