### ISSUE TITLE
is it necessary for the user to install keras?

### ISSUE THREAD

**Issue by goodfeli** [openai/cleverhans#9]
ideally we would only need keras for the tutorial, so that people using other frameworks can run the benchmarks

**Comment by goodfeli** [comment]
I think let's make sure people can import the attacks and run them without needing any particular framework. e.g., it should work if the user has only theano, or if the user has only tensorflow. It's OK for the tutorial to use keras.

**Comment by npapernot** [comment]
It should not be the case anymore, now that the attacks module has been refactored. All keras dependencies are cleared as far as I know. Feel free to reopen if I missed anything.
